"""Dev helper: bulk-insert a starter word catalog.

Also used as the canonical data source for the test fixture at
tests/fixtures/seed_words.py, so unit/integration tests exercise the same
~40-word catalog a fresh dev environment gets. Run standalone with:

    python -m scripts.seed_dev_words
"""

import asyncio
from typing import Any

from bot.database.models.enums import CEFRLevel, PartOfSpeech, WordSource
from bot.database.models.word import Word
from bot.database.session import get_session

SEED_WORDS: list[dict[str, Any]] = [
    {
        "lemma": "buy",
        "translation": "купувати",
        "example_en": "I need to buy some milk.",
        "example_uk": "Мені потрібно купити молоко.",
        "level": CEFRLevel.A1,
        "part_of_speech": PartOfSpeech.VERB,
        "topic": "shopping",
        "transcription_uk": "/baɪ/",
        "transcription_us": "/baɪ/",
    },
    {
        "lemma": "house",
        "translation": "будинок",
        "example_en": "They live in a small house.",
        "example_uk": "Вони живуть у маленькому будинку.",
        "level": CEFRLevel.A1,
        "part_of_speech": PartOfSpeech.NOUN,
        "topic": "home",
        "transcription_uk": "/haʊs/",
        "transcription_us": "/haʊs/",
    },
    {
        "lemma": "happy",
        "translation": "щасливий",
        "example_en": "She feels happy today.",
        "example_uk": "Сьогодні вона почувається щасливою.",
        "level": CEFRLevel.A1,
        "part_of_speech": PartOfSpeech.ADJECTIVE,
        "topic": "emotions",
        "transcription_uk": "/ˈhæpi/",
        "transcription_us": "/ˈhæpi/",
    },
    {
        "lemma": "quickly",
        "translation": "швидко",
        "example_en": "He ran quickly to the bus stop.",
        "example_uk": "Він швидко побіг до автобусної зупинки.",
        "level": CEFRLevel.A1,
        "part_of_speech": PartOfSpeech.ADVERB,
        "topic": "movement",
        "transcription_uk": "/ˈkwɪkli/",
        "transcription_us": "/ˈkwɪkli/",
    },
    {
        "lemma": "in front of",
        "translation": "перед",
        "example_en": "The car is parked in front of the house.",
        "example_uk": "Машина припаркована перед будинком.",
        "level": CEFRLevel.A1,
        "part_of_speech": PartOfSpeech.PREPOSITION,
        "topic": "location",
        "transcription_uk": "/ɪn frʌnt əv/",
        "transcription_us": "/ɪn frʌnt əv/",
    },
    {
        "lemma": "and",
        "translation": "і, та",
        "example_en": "I like tea and coffee.",
        "example_uk": "Мені подобається чай і кава.",
        "level": CEFRLevel.A1,
        "part_of_speech": PartOfSpeech.CONJUNCTION,
        "topic": "general",
        "transcription_uk": "/ænd/",
        "transcription_us": "/ænd/",
    },
    {
        "lemma": "school",
        "translation": "школа",
        "example_en": "My children go to school by bus.",
        "example_uk": "Мої діти їздять до школи автобусом.",
        "level": CEFRLevel.A1,
        "part_of_speech": PartOfSpeech.NOUN,
        "topic": "education",
        "transcription_uk": "/skuːl/",
        "transcription_us": "/skuːl/",
    },
    {
        "lemma": "eat",
        "translation": "їсти",
        "example_en": "We usually eat dinner at seven.",
        "example_uk": "Ми зазвичай вечеряємо о сьомій.",
        "level": CEFRLevel.A1,
        "part_of_speech": PartOfSpeech.VERB,
        "topic": "food",
        "transcription_uk": "/iːt/",
        "transcription_us": "/iːt/",
    },
    {
        "lemma": "big",
        "translation": "великий",
        "example_en": "They bought a big table.",
        "example_uk": "Вони купили великий стіл.",
        "level": CEFRLevel.A1,
        "part_of_speech": PartOfSpeech.ADJECTIVE,
        "topic": "size",
        "transcription_uk": "/bɪɡ/",
        "transcription_us": "/bɪɡ/",
    },
    {
        "lemma": "water",
        "translation": "вода",
        "example_en": "Please drink more water every day.",
        "example_uk": "Будь ласка, пий більше води щодня.",
        "level": CEFRLevel.A1,
        "part_of_speech": PartOfSpeech.NOUN,
        "topic": "food",
        "transcription_uk": "/ˈwɔːtə/",
        "transcription_us": "/ˈwɑːtər/",
    },
    {
        "lemma": "purchase",
        "translation": "купувати, придбавати",
        "example_en": "You can purchase tickets online.",
        "example_uk": "Ви можете придбати квитки онлайн.",
        "level": CEFRLevel.A2,
        "part_of_speech": PartOfSpeech.VERB,
        "topic": "shopping",
        "transcription_uk": "/ˈpɜːtʃəs/",
        "transcription_us": "/ˈpɜːrtʃəs/",
        "synonyms": ["buy"],
    },
    {
        "lemma": "expensive",
        "translation": "дорогий",
        "example_en": "This restaurant is too expensive for us.",
        "example_uk": "Цей ресторан для нас занадто дорогий.",
        "level": CEFRLevel.A2,
        "part_of_speech": PartOfSpeech.ADJECTIVE,
        "topic": "money",
        "transcription_uk": "/ɪkˈspensɪv/",
        "transcription_us": "/ɪkˈspensɪv/",
    },
    {
        "lemma": "give up",
        "translation": "здаватися, кидати",
        "example_en": "Don't give up on your dream.",
        "example_uk": "Не здавайся щодо своєї мрії.",
        "level": CEFRLevel.A2,
        "part_of_speech": PartOfSpeech.PHRASAL_VERB,
        "topic": "motivation",
        "transcription_uk": "/ɡɪv ʌp/",
        "transcription_us": "/ɡɪv ʌp/",
    },
    {
        "lemma": "look forward to",
        "translation": "з нетерпінням чекати",
        "example_en": "I look forward to seeing you.",
        "example_uk": "Я з нетерпінням чекаю на зустріч з тобою.",
        "level": CEFRLevel.A2,
        "part_of_speech": PartOfSpeech.PHRASAL_VERB,
        "topic": "emotions",
        "transcription_uk": "/lʊk ˈfɔːwəd tuː/",
        "transcription_us": "/lʊk ˈfɔːrwərd tuː/",
    },
    {
        "lemma": "although",
        "translation": "хоча, незважаючи на те що",
        "example_en": "Although it was raining, we went for a walk.",
        "example_uk": "Хоча йшов дощ, ми пішли на прогулянку.",
        "level": CEFRLevel.A2,
        "part_of_speech": PartOfSpeech.CONJUNCTION,
        "topic": "general",
        "transcription_uk": "/ɔːlˈðəʊ/",
        "transcription_us": "/ɔːlˈðoʊ/",
    },
    {
        "lemma": "borrow",
        "translation": "позичати",
        "example_en": "Can I borrow your pen for a minute?",
        "example_uk": "Можна позичити твою ручку на хвилину?",
        "level": CEFRLevel.A2,
        "part_of_speech": PartOfSpeech.VERB,
        "topic": "money",
        "transcription_uk": "/ˈbɒrəʊ/",
        "transcription_us": "/ˈbɑːroʊ/",
    },
    {
        "lemma": "comfortable",
        "translation": "зручний",
        "example_en": "This chair is very comfortable.",
        "example_uk": "Цей стілець дуже зручний.",
        "level": CEFRLevel.A2,
        "part_of_speech": PartOfSpeech.ADJECTIVE,
        "topic": "home",
        "transcription_uk": "/ˈkʌmftəbl/",
        "transcription_us": "/ˈkʌmfərtəbl/",
    },
    {
        "lemma": "rarely",
        "translation": "рідко",
        "example_en": "She rarely goes to the cinema.",
        "example_uk": "Вона рідко ходить у кіно.",
        "level": CEFRLevel.A2,
        "part_of_speech": PartOfSpeech.ADVERB,
        "topic": "frequency",
        "transcription_uk": "/ˈreəli/",
        "transcription_us": "/ˈrerli/",
    },
    {
        "lemma": "get along with",
        "translation": "ладнати з",
        "example_en": "I get along with my neighbors well.",
        "example_uk": "Я добре ладнаю зі своїми сусідами.",
        "level": CEFRLevel.A2,
        "part_of_speech": PartOfSpeech.PHRASAL_VERB,
        "topic": "relationships",
        "transcription_uk": "/ɡet əˈlɒŋ wɪð/",
        "transcription_us": "/ɡet əˈlɔːŋ wɪð/",
    },
    {
        "lemma": "journey",
        "translation": "подорож",
        "example_en": "Our journey to the coast took five hours.",
        "example_uk": "Наша подорож до узбережжя тривала п'ять годин.",
        "level": CEFRLevel.A2,
        "part_of_speech": PartOfSpeech.NOUN,
        "topic": "travel",
        "transcription_uk": "/ˈdʒɜːni/",
        "transcription_us": "/ˈdʒɜːrni/",
    },
    {
        "lemma": "affordable",
        "translation": "доступний за ціною, недорогий",
        "example_en": "This restaurant is affordable for students.",
        "example_uk": "Цей ресторан доступний за ціною для студентів.",
        "level": CEFRLevel.B1,
        "part_of_speech": PartOfSpeech.ADJECTIVE,
        "topic": "money",
        "transcription_uk": "/əˈfɔːdəbl/",
        "transcription_us": "/əˈfɔːrdəbl/",
        "synonyms": ["cheap", "inexpensive"],
        "antonyms": ["expensive"],
    },
    {
        "lemma": "achieve",
        "translation": "досягати",
        "example_en": "She worked hard to achieve her goals.",
        "example_uk": "Вона наполегливо працювала, щоб досягти своїх цілей.",
        "level": CEFRLevel.B1,
        "part_of_speech": PartOfSpeech.VERB,
        "topic": "motivation",
        "transcription_uk": "/əˈtʃiːv/",
        "transcription_us": "/əˈtʃiːv/",
    },
    {
        "lemma": "reliable",
        "translation": "надійний",
        "example_en": "He is a reliable and honest colleague.",
        "example_uk": "Він надійний і чесний колега.",
        "level": CEFRLevel.B1,
        "part_of_speech": PartOfSpeech.ADJECTIVE,
        "topic": "character",
        "transcription_uk": "/rɪˈlaɪəbl/",
        "transcription_us": "/rɪˈlaɪəbl/",
    },
    {
        "lemma": "eventually",
        "translation": "врешті-решт",
        "example_en": "Eventually, they found a solution.",
        "example_uk": "Врешті-решт вони знайшли рішення.",
        "level": CEFRLevel.B1,
        "part_of_speech": PartOfSpeech.ADVERB,
        "topic": "general",
        "transcription_uk": "/ɪˈventʃuəli/",
        "transcription_us": "/ɪˈventʃuəli/",
    },
    {
        "lemma": "put off",
        "translation": "відкладати",
        "example_en": "We had to put off the meeting until Friday.",
        "example_uk": "Нам довелося відкласти зустріч до п'ятниці.",
        "level": CEFRLevel.B1,
        "part_of_speech": PartOfSpeech.PHRASAL_VERB,
        "topic": "work",
        "transcription_uk": "/pʊt ɒf/",
        "transcription_us": "/pʊt ɔːf/",
    },
    {
        "lemma": "break the ice",
        "translation": "розтопити лід (про спілкування)",
        "example_en": "He told a joke to break the ice at the meeting.",
        "example_uk": "Він розповів жарт, щоб розтопити лід на зустрічі.",
        "level": CEFRLevel.B1,
        "part_of_speech": PartOfSpeech.IDIOM,
        "topic": "relationships",
        "transcription_uk": "/breɪk ði aɪs/",
        "transcription_us": "/breɪk ði aɪs/",
    },
    {
        "lemma": "consequently",
        "translation": "отже, внаслідок цього",
        "example_en": "The flight was delayed; consequently, we missed the connection.",
        "example_uk": "Рейс затримали, внаслідок чого ми пропустили пересадку.",
        "level": CEFRLevel.B1,
        "part_of_speech": PartOfSpeech.CONJUNCTION,
        "topic": "general",
        "transcription_uk": "/ˈkɒnsɪkwəntli/",
        "transcription_us": "/ˈkɑːnsɪkwəntli/",
    },
    {
        "lemma": "despite",
        "translation": "незважаючи на",
        "example_en": "Despite the rain, the match continued.",
        "example_uk": "Незважаючи на дощ, матч тривав.",
        "level": CEFRLevel.B1,
        "part_of_speech": PartOfSpeech.PREPOSITION,
        "topic": "general",
        "transcription_uk": "/dɪˈspaɪt/",
        "transcription_us": "/dɪˈspaɪt/",
    },
    {
        "lemma": "opportunity",
        "translation": "можливість",
        "example_en": "This job is a great opportunity for her.",
        "example_uk": "Ця робота — чудова можливість для неї.",
        "level": CEFRLevel.B1,
        "part_of_speech": PartOfSpeech.NOUN,
        "topic": "work",
        "transcription_uk": "/ˌɒpəˈtjuːnəti/",
        "transcription_us": "/ˌɑːpərˈtuːnəti/",
    },
    {
        "lemma": "generous",
        "translation": "щедрий",
        "example_en": "He is very generous with his time.",
        "example_uk": "Він дуже щедрий на свій час.",
        "level": CEFRLevel.B1,
        "part_of_speech": PartOfSpeech.ADJECTIVE,
        "topic": "character",
        "transcription_uk": "/ˈdʒenərəs/",
        "transcription_us": "/ˈdʒenərəs/",
    },
    {
        "lemma": "figure out",
        "translation": "зрозуміти, з'ясувати",
        "example_en": "I need to figure out how this works.",
        "example_uk": "Мені потрібно зрозуміти, як це працює.",
        "level": CEFRLevel.B1,
        "part_of_speech": PartOfSpeech.PHRASAL_VERB,
        "topic": "general",
        "transcription_uk": "/ˈfɪɡər aʊt/",
        "transcription_us": "/ˈfɪɡjər aʊt/",
    },
    {
        "lemma": "convenient",
        "translation": "зручний, слушний",
        "example_en": "Is Monday a convenient day for the meeting?",
        "example_uk": "Понеділок — зручний день для зустрічі?",
        "level": CEFRLevel.B1,
        "part_of_speech": PartOfSpeech.ADJECTIVE,
        "topic": "planning",
        "transcription_uk": "/kənˈviːniənt/",
        "transcription_us": "/kənˈviːniənt/",
    },
    {
        "lemma": "on the other hand",
        "translation": "з іншого боку",
        "example_en": "The flat is cheap; on the other hand, it's far from the center.",
        "example_uk": "Квартира дешева, з іншого боку — далеко від центру.",
        "level": CEFRLevel.B1,
        "part_of_speech": PartOfSpeech.PHRASE,
        "topic": "general",
        "transcription_uk": "/ɒn ði ˈʌðə hænd/",
        "transcription_us": "/ɑːn ði ˈʌðər hænd/",
    },
    {
        "lemma": "improve",
        "translation": "покращувати",
        "example_en": "She wants to improve her English quickly.",
        "example_uk": "Вона хоче швидко покращити свою англійську.",
        "level": CEFRLevel.B1,
        "part_of_speech": PartOfSpeech.VERB,
        "topic": "education",
        "transcription_uk": "/ɪmˈpruːv/",
        "transcription_us": "/ɪmˈpruːv/",
    },
    {
        "lemma": "budget",
        "translation": "бюджет",
        "example_en": "We need to stick to our travel budget.",
        "example_uk": "Нам потрібно дотримуватися нашого бюджету на подорож.",
        "level": CEFRLevel.B1,
        "part_of_speech": PartOfSpeech.NOUN,
        "topic": "money",
        "transcription_uk": "/ˈbʌdʒɪt/",
        "transcription_us": "/ˈbʌdʒɪt/",
    },
    {
        "lemma": "under the weather",
        "translation": "погано почуватися",
        "example_en": "I'm feeling a bit under the weather today.",
        "example_uk": "Сьогодні я почуваюся не дуже добре.",
        "level": CEFRLevel.B1,
        "part_of_speech": PartOfSpeech.IDIOM,
        "topic": "health",
        "transcription_uk": "/ˈʌndə ðə ˈweðə/",
        "transcription_us": "/ˈʌndər ðə ˈweðər/",
    },
    {
        "lemma": "in order to",
        "translation": "для того щоб",
        "example_en": "She saved money in order to buy a car.",
        "example_uk": "Вона заощаджувала гроші, щоб купити машину.",
        "level": CEFRLevel.B1,
        "part_of_speech": PartOfSpeech.CONJUNCTION,
        "topic": "general",
        "transcription_uk": "/ɪn ˈɔːdə tuː/",
        "transcription_us": "/ɪn ˈɔːrdər tuː/",
    },
    {
        "lemma": "worthwhile",
        "translation": "вартий уваги, вартий того",
        "example_en": "Learning a new language is always worthwhile.",
        "example_uk": "Вивчення нової мови завжди того варте.",
        "level": CEFRLevel.B1,
        "part_of_speech": PartOfSpeech.ADJECTIVE,
        "topic": "education",
        "transcription_uk": "/ˌwɜːθˈwaɪl/",
        "transcription_us": "/ˌwɜːrθˈwaɪl/",
    },
    {
        "lemma": "cope with",
        "translation": "справлятися з",
        "example_en": "It's hard to cope with so much stress.",
        "example_uk": "Важко справлятися з таким сильним стресом.",
        "level": CEFRLevel.B1,
        "part_of_speech": PartOfSpeech.PHRASAL_VERB,
        "topic": "health",
        "transcription_uk": "/kəʊp wɪð/",
        "transcription_us": "/koʊp wɪð/",
    },
    {
        "lemma": "nevertheless",
        "translation": "тим не менш",
        "example_en": "It was raining; nevertheless, we went out.",
        "example_uk": "Йшов дощ, тим не менш ми вийшли надвір.",
        "level": CEFRLevel.B1,
        "part_of_speech": PartOfSpeech.OTHER,
        "topic": "general",
        "transcription_uk": "/ˌnevəðəˈles/",
        "transcription_us": "/ˌnevərðəˈles/",
    },
]


def build_word(item: dict[str, Any]) -> Word:
    return Word(
        lemma=item["lemma"],
        translation=item["translation"],
        example_en=item["example_en"],
        example_uk=item["example_uk"],
        level=item["level"],
        part_of_speech=item["part_of_speech"],
        topic=item.get("topic"),
        transcription_uk=item.get("transcription_uk"),
        transcription_us=item.get("transcription_us"),
        synonyms=item.get("synonyms", []),
        antonyms=item.get("antonyms", []),
        collocations=item.get("collocations", []),
        source=WordSource.SEED,
    )


async def seed(*, skip_existing: bool = True) -> list[Word]:
    from sqlalchemy import select

    inserted: list[Word] = []
    async with get_session() as session:
        for item in SEED_WORDS:
            if skip_existing:
                existing = await session.execute(
                    select(Word).where(
                        Word.lemma == item["lemma"], Word.part_of_speech == item["part_of_speech"]
                    )
                )
                if existing.scalar_one_or_none() is not None:
                    continue

            word = build_word(item)
            session.add(word)
            inserted.append(word)

        await session.flush()

    return inserted


if __name__ == "__main__":
    words = asyncio.run(seed())
    print(f"Inserted {len(words)} seed words.")
